NoteSimpleWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('ns_web.urls')),
]

ns_web/urls.py
from django.urls import path

from .import views

app_name = 'ns_web'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),

    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

    # Page for deleting an entry.
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),

    # Deleting a topic and its entries.
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='delete_topic')

]

users/urls.py
"""Define URL patterns for users"""

from django.urls import path, include

from . import views


app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

ns_web/models.py
from django.db import models
from django.contrib.auth.models import User


# More details about models can be found at:
# https://docs.djangoproject.com/en/2.2/ref/models/fields/

class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)  # 200 was chosen to cover most topic names.
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)  # Cascading delete: Deletes all corresponding entries
    # ForeignKey connects the information to another location in the database.
    # It indicates that entries are a subsidiary of Topics.
    text = models.TextField()  # Unlimited length.
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        """This holds extra information for the Entry class."""
        verbose_name_plural = 'entries'
        # Without this line Django would refer to multiple entries as "Entrys"

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"
        # Which information to show when referring to individual entries.
        # First 50 characters are shown as the text can be longer. We also indicate that it may be longer.

users/models.py
from django.db import models

# Create your models here.

ns_web/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

ns_web/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """The home page for Learning Logs."""
    return render(request, 'ns_web/index.html')


@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'ns_web/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'ns_web/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted, process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('ns_web:topics')

    # Display a blank or valid form.
    context = {'form': form}
    return render(request, 'ns_web/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('ns_web:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'ns_web/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('ns_web:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'ns_web/edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    """Delete an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    else:
        entry.delete()
        return redirect('ns_web:topic', topic_id=topic.id)


@login_required
def delete_topic(request, topic_id):
    """Delete a topic and its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    topic.delete()
    entries.delete()
    context = {'topic': topic, 'entries': entries}
    return render(request, 'ns_web/topics.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display a blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('ns_web:index')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

ns_web/templates/ns_web/base.html
{%  load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="with=device-width , initial-scale=1,
          shrink-to-fit=no">
    <title>NoteSimple</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'ns_web:topics' %}">
                NoteSimple</a>
       {% else %}
        <a class="navbar-brand" href="{% url 'ns_web:index' %}">
            NoteSimple</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ns_web:topics' %}">
                        Topics</a></li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
            {% block content %} {% endblock content %}
    </main>

</body>

</html>

ns_web/templates/ns_web/edit_entry.html
{% extends 'ns_web/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit entry</h2>
{% endblock page_header %}

{% block content %}

    <h5><a href="{% url 'ns_web:topic' topic.id %}">{{ topic }}</a></h5>


    <form method="post" action="{% url 'ns_web:edit_entry' entry.id %}" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        {% buttons %}
        <button name="submit" class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

ns_web/templates/ns_web/index.html
{% extends "ns_web/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Note taking, simplified.</h1>

        <p class="lead">Keep track of your notes in a secure an private way.
        NoteSimple is a web-app that is completely free and easy to use. Whether it be diary
        entries or TODO lists, you can access them wherever you are.</p>

        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
           role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

ns_web/templates/ns_web/new_entry.html
{% extends "ns_web/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>New entry</h2>
{% endblock page_header %}

{% block content %}

    <h5><a href="{% url 'ns_web:topic' topic.id %}">{{ topic }}</a></h5>

    <form method="post" action="{% url 'ns_web:new_entry' topic.id %}" class='form'>
        {% csrf_token %}
        {{ form.as_p }}
        {% buttons %}
        <button name='submit' class="btn btn-primary">Add entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

ns_web/templates/ns_web/new_topic.html
{% extends "ns_web/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Add new topic</h2>
{% endblock page_header %}

{% block content %}
    <form method="post" action="{% url 'ns_web:new_topic' %}" class='form'>
        {% csrf_token %}
        {{ form.as_p }}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Create topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

ns_web/templates/ns_web/topic.html
{% extends 'ns_web/base.html' %}

{% block page_header %}
    <h3>{{ topic}}</h3>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'ns_web:new_entry' topic.id %}">Add new entry</a>
    </p>
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small><a href="{% url 'ns_web:edit_entry' entry.id %}">
                    edit entry</a></small>
                <small><a href="{% url 'ns_web:delete_entry' entry.id %}">
                    delete entry</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}
    <a href="{% url 'ns_web:delete_topic' topic.id %}">
            Delete Topic
        </a>

{% endblock content %}

ns_web/templates/ns_web/topics.html
{% extends "ns_web/base.html" %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li><h3>
                <a href="{% url 'ns_web:topic' topic.id %}">{{ topic }}</a>
            </h3></li>
        {%  empty %}
            <li><h3>No topics have been added yet.</h3></li>
        {%  endfor %}
    </ul>

    <h3><a href="{% url 'ns_web:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}